apiVersion: v2
name: cave-crossplane
description: Cave Runtime — cave-crossplane (port of Crossplane v2.3.1)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/LordGnomish/cave-runtime
sources:
  - https://github.com/LordGnomish/cave-runtime
maintainers:
  - name: Burak Tartan
    email: btartan@gmail.com
keywords:
  - cave-runtime
  - cave-crossplane
