apiVersion: v2
name: cave-incidents
description: Cave Runtime — cave-incidents (port of Incident response service)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/LordGnomish/cave-runtime
sources:
  - https://github.com/LordGnomish/cave-runtime
maintainers:
  - name: Burak Tartan
    email: btartan@gmail.com
keywords:
  - cave-runtime
  - cave-incidents
