apiVersion: v2
name: cave-cri
description: Cave Runtime — cave-cri (port of Container Runtime Interface)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/LordGnomish/cave-runtime
sources:
  - https://github.com/LordGnomish/cave-runtime
maintainers:
  - name: Burak Tartan
    email: btartan@gmail.com
keywords:
  - cave-runtime
  - cave-cri
