apiVersion: v2
name: cave-gateway
description: Cave Runtime — cave-gateway (port of Kong 3.9.1 + Gravitee 4.11.7)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/LordGnomish/cave-runtime
sources:
  - https://github.com/LordGnomish/cave-runtime
maintainers:
  - name: Burak Tartan
    email: btartan@gmail.com
keywords:
  - cave-runtime
  - cave-gateway
