// SPDX-License-Identifier: AGPL-3.0-or-later
// Source: META — cave-artifacts core::signature (consolidates cosign + Pulp SigningService)
//! `Signature` — cosign-shape signature record attached to a target digest.
//!
//! Maps to:
//! - sigstore/cosign `oci.Signature` (sigstore/cosign@HEAD pkg/oci/signature.go)
//! - pulpcore `SigningService` (pulpcore/app/models/content.py)
//! - cave-artifacts `cosign::` module — the per-alg crypto implementation

use serde::{Deserialize, Serialize};

/// Wire identifier for the signature algorithm.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SignatureAlg {
    /// Classic ECDSA over secp256r1 / NIST P-256 + SHA-256.
    EcdsaP256,
    /// Pure-Rust Ed25519 (RFC 8032).
    Ed25519,
    /// NIST PQC ML-DSA-65 (FIPS 204).
    MlDsa65,
    /// Composite hybrid Ed25519 + ML-DSA-65 (Cave default for new keys).
    HybridEd25519MlDsa65,
}

impl SignatureAlg {
    pub fn as_wire(&self) -> &'static str {
        match self {
            Self::EcdsaP256 => "ecdsa-p256",
            Self::Ed25519 => "ed25519",
            Self::MlDsa65 => "ml-dsa-65",
            Self::HybridEd25519MlDsa65 => "hybrid-ed25519-ml-dsa-65",
        }
    }
}

/// Signed pointer at a target digest.  Generated by the `cosign::` module
/// and recorded against [`crate::core::Tag::signed_with`] so the portal
/// signature-coverage panel can show what fraction of pushes are signed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Signature {
    pub alg: SignatureAlg,
    /// Identity of the signer (cosign-style email/identity, or "key:<id>").
    pub signer: String,
    /// Raw signature bytes, base64-url-no-pad encoded for transport.
    pub value: String,
    /// Digest the signature applies to (`sha256:<hex>` of the artifact).
    pub target_digest: String,
}

impl Signature {
    pub fn new(
        alg: SignatureAlg,
        signer: impl Into<String>,
        value: impl Into<String>,
        target_digest: impl Into<String>,
    ) -> Self {
        Self {
            alg,
            signer: signer.into(),
            value: value.into(),
            target_digest: target_digest.into(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn alg_wire_strings_are_stable() {
        assert_eq!(SignatureAlg::EcdsaP256.as_wire(), "ecdsa-p256");
        assert_eq!(SignatureAlg::Ed25519.as_wire(), "ed25519");
        assert_eq!(SignatureAlg::MlDsa65.as_wire(), "ml-dsa-65");
        assert_eq!(
            SignatureAlg::HybridEd25519MlDsa65.as_wire(),
            "hybrid-ed25519-ml-dsa-65"
        );
    }

    #[test]
    fn signature_constructor_and_serde() {
        let s = Signature::new(
            SignatureAlg::EcdsaP256,
            "alice@cave.dev",
            "MEUCIQ…",
            "sha256:cafe",
        );
        assert_eq!(s.signer, "alice@cave.dev");
        let j = serde_json::to_string(&s).unwrap();
        assert!(j.contains("\"alg\":\"ecdsa-p256\""));
        let back: Signature = serde_json::from_str(&j).unwrap();
        assert_eq!(s, back);
    }
}
