//! TechDocs data models — port of Backstage TechDocs types.
//!
//! Upstream: @backstage/techdocs-common TechDocsMetadata, EntityName, EntityMetadata

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Identifies a Backstage entity (namespace/kind/name triplet).
///
/// Upstream: EntityName in @backstage/catalog-model
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EntityName {
    pub namespace: String,
    pub kind: String,
    pub name: String,
}

impl EntityName {
    pub fn new(namespace: impl Into<String>, kind: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            namespace: namespace.into(),
            kind: kind.into(),
            name: name.into(),
        }
    }
}

/// Metadata stored in `techdocs_metadata.json` (generated by mkdocs).
///
/// Upstream: TechDocsMetadata in @backstage/techdocs-common
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TechDocsMetadata {
    pub site_name: String,
    pub site_description: String,
    pub etag: String,
    pub build_timestamp: i64,
    pub files: Vec<String>,
}

/// Backstage entity metadata shape (subset for TechDocs responses).
///
/// Upstream: Entity in @backstage/catalog-model
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntityMetadata {
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    pub kind: String,
    pub metadata: EntityMetadataInner,
    pub spec: serde_json::Value,
}

/// Inner metadata block within an entity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntityMetadataInner {
    pub namespace: String,
    pub name: String,
    pub description: Option<String>,
    pub annotations: HashMap<String, String>,
    pub labels: HashMap<String, String>,
    pub uid: String,
}
