//! Draft document model — frontmatter, rendering, and Ollama prompt construction.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Publication status of a generated draft.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DraftStatus {
    Draft,
    InProgress,
    Done,
}

impl std::fmt::Display for DraftStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DraftStatus::Draft => write!(f, "draft"),
            DraftStatus::InProgress => write!(f, "in_progress"),
            DraftStatus::Done => write!(f, "done"),
        }
    }
}

/// YAML frontmatter fields written at the top of every draft document.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DraftFrontmatter {
    pub crate_name: String,
    pub upstream_repo: String,
    /// Source file path in the upstream repo.
    pub upstream_file: String,
    /// Function name in the upstream repo.
    pub upstream_fn: String,
    pub status: DraftStatus,
    /// Tier 1 = generated skeleton; Tier 2 = filled in; Tier 3 = passing; Tier 4 = merged.
    pub tier: u8,
    pub created_at: DateTime<Utc>,
}

/// A fully renderable draft: frontmatter + Ollama-generated failing test + skeleton.
#[derive(Debug, Clone)]
pub struct Draft {
    pub frontmatter: DraftFrontmatter,
    /// Failing `#[tokio::test]` generated by Ollama.
    pub failing_test: String,
    /// Function skeleton generated by Ollama (may contain `todo!()`).
    pub skeleton: String,
}

impl Draft {
    /// Renders the draft to a Markdown document with YAML frontmatter.
    pub fn render(&self) -> String {
        let fm = &self.frontmatter;
        format!(
            "---\n\
             crate: {crate}\n\
             upstream_repo: {repo}\n\
             upstream_file: {file}\n\
             upstream_fn: {fn_}\n\
             status: {status}\n\
             tier: {tier}\n\
             created_at: {ts}\n\
             ---\n\n\
             ## Upstream reference\n\n\
             `{repo}` → `{file}` → `{fn_}`\n\n\
             ## Failing test\n\n\
             ```rust\n{test}\n```\n\n\
             ## Implementation skeleton\n\n\
             ```rust\n{skel}\n```\n",
            crate = fm.crate_name,
            repo = fm.upstream_repo,
            file = fm.upstream_file,
            fn_ = fm.upstream_fn,
            status = fm.status,
            tier = fm.tier,
            ts = fm.created_at.to_rfc3339(),
            test = self.failing_test,
            skel = self.skeleton,
        )
    }
}

/// Returns the canonical filename for a draft, e.g. `2026-04-22-cave-secrets-scan_file.md`.
pub fn draft_filename(crate_name: &str, local_fn: &str, at: DateTime<Utc>) -> String {
    format!("{}-{}-{}.md", at.format("%Y-%m-%d"), crate_name, local_fn)
}

/// Builds the Ollama prompt for generating a failing test + implementation skeleton.
pub fn build_ollama_prompt(
    crate_name: &str,
    local_fn: &str,
    upstream_repo: &str,
    upstream_fn: &str,
    upstream_file: &str,
) -> String {
    format!(
        "You are implementing the Cave Runtime platform, a sovereign cloud OS in Rust.\n\n\
         Task: implement `{local_fn}` in crate `{crate_name}`, mirroring `{upstream_fn}` \
         from `{upstream_repo}` (upstream file: `{upstream_file}`).\n\n\
         Generate exactly two sections:\n\n\
         ## Test\n\
         A single `#[tokio::test]` that exercises `{local_fn}` with realistic inputs \
         and asserts the expected behaviour. Do not leave the body empty.\n\n\
         ## Implementation\n\
         A `pub` function named `{local_fn}` with the correct signature inferred from \
         the test. The body may use `todo!(\"Tier 2\")` for unimplemented logic.\n\n\
         Output ONLY the two sections above — no prose, no extra headings.",
        local_fn = local_fn,
        crate_name = crate_name,
        upstream_fn = upstream_fn,
        upstream_repo = upstream_repo,
        upstream_file = upstream_file,
    )
}

/// Extracts the `## Test` and `## Implementation` sections from an Ollama response.
///
/// Returns `(failing_test_code, skeleton_code)`. Missing sections are returned as empty strings.
pub fn parse_ollama_response(response: &str) -> (String, String) {
    let test = extract_rust_fence(response, "## Test");
    let skel = extract_rust_fence(response, "## Implementation");
    (test, skel)
}

/// Finds the first ```rust … ``` fence after `heading` in `text`.
fn extract_rust_fence(text: &str, heading: &str) -> String {
    let Some(heading_pos) = text.find(heading) else {
        return String::new();
    };
    let after = &text[heading_pos + heading.len()..];

    let Some(fence_start) = after.find("```rust") else {
        // Fallback: text between heading and next ## (or end)
        let end = after[1..].find("\n## ").map(|i| i + 1).unwrap_or(after.len());
        return after[..end].trim().to_string();
    };

    let code_start = fence_start + "```rust".len();
    let remaining = &after[code_start..];

    let Some(fence_end) = remaining.find("```") else {
        return remaining.trim().to_string();
    };

    remaining[..fence_end].trim().to_string()
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn sample_draft() -> Draft {
        Draft {
            frontmatter: DraftFrontmatter {
                crate_name: "cave-secrets".into(),
                upstream_repo: "trufflesecurity/trufflehog".into(),
                upstream_file: "pkg/sources/filesystem/filesystem.go".into(),
                upstream_fn: "ScanFile".into(),
                status: DraftStatus::Draft,
                tier: 1,
                created_at: Utc.with_ymd_and_hms(2026, 4, 22, 10, 0, 0).unwrap(),
            },
            failing_test: "// test stub".into(),
            skeleton: "// impl stub".into(),
        }
    }

    #[test]
    fn test_draft_render_starts_with_frontmatter() {
        let rendered = sample_draft().render();
        assert!(rendered.starts_with("---\n"), "must start with YAML frontmatter fence");
        assert!(rendered.contains("crate: cave-secrets"));
        assert!(rendered.contains("status: draft"));
        assert!(rendered.contains("tier: 1"));
        assert!(rendered.contains("upstream_fn: ScanFile"));
        assert!(rendered.contains("created_at: 2026-04-22T10:00:00+00:00"));
    }

    #[test]
    fn test_draft_render_contains_code_fences() {
        let rendered = sample_draft().render();
        assert!(rendered.contains("```rust\n// test stub\n```"));
        assert!(rendered.contains("```rust\n// impl stub\n```"));
    }

    #[test]
    fn test_draft_filename_format() {
        let dt = Utc.with_ymd_and_hms(2026, 4, 22, 10, 0, 0).unwrap();
        assert_eq!(
            draft_filename("cave-secrets", "scan_file", dt),
            "2026-04-22-cave-secrets-scan_file.md"
        );
    }

    #[test]
    fn test_parse_ollama_response_extracts_both_sections() {
        let response = r#"## Test
```rust
#[tokio::test]
async fn test_scan_file() { assert!(true); }
```

## Implementation
```rust
pub async fn scan_file(path: &std::path::Path) -> bool { todo!("Tier 2") }
```"#;
        let (test, skel) = parse_ollama_response(response);
        assert!(test.contains("async fn test_scan_file()"), "test: {test}");
        assert!(skel.contains("pub async fn scan_file"), "skel: {skel}");
    }

    #[test]
    fn test_parse_ollama_response_missing_section_returns_empty() {
        let (test, skel) = parse_ollama_response("no sections here");
        assert!(test.is_empty());
        assert!(skel.is_empty());
    }

    #[test]
    fn test_build_ollama_prompt_contains_function_names() {
        let prompt = build_ollama_prompt(
            "cave-secrets",
            "scan_file",
            "trufflesecurity/trufflehog",
            "ScanFile",
            "pkg/sources/filesystem/filesystem.go",
        );
        assert!(prompt.contains("`scan_file`"));
        assert!(prompt.contains("`ScanFile`"));
        assert!(prompt.contains("cave-secrets"));
        assert!(prompt.contains("## Test"));
        assert!(prompt.contains("## Implementation"));
    }
}
