// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2026 Cave Runtime contributors
//! Compile-before-commit probe.
//!
//! Given a skeleton extracted from an Ollama response, [`DraftProbe`] writes
//! a throwaway single-file Cargo package and runs `cargo check` against it.
//! The probe crate has **no dependencies** (not even the target crate) —
//! this is deliberate.  A tier-1 draft is a signature plus `todo!("Tier 2")`
//! and, per the hardened prompt in [`crate::draft`], must only reference
//! `std` / primitive types.  Any `use foo::…` that escapes to an external
//! crate will fail the probe, which is exactly what we want: the model
//! regularly hallucinates dependencies like `cave_commons::types::Secret`
//! that do not exist in the workspace, and those hallucinations are the
//! dominant source of `compile_fail` escalations in production.
//!
//! The probe lives under `<repo>/target/cave-local-llm-drafts/<probe_id>/`
//! so it reuses the workspace's target directory and does not litter the
//! source tree.

use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use chrono::Utc;

/// Outcome of a single `cargo check` probe.
#[derive(Debug, Clone)]
pub enum ProbeOutcome {
    /// `cargo check` exited 0 — the skeleton compiles in isolation.
    Ok,
    /// `cargo check` exited non-zero — the skeleton is malformed.
    Fail {
        exit_code: Option<i32>,
        stdout: String,
        stderr: String,
    },
    /// `cargo check` exceeded the configured timeout.
    Timeout { elapsed: Duration },
}

impl ProbeOutcome {
    pub fn is_ok(&self) -> bool {
        matches!(self, ProbeOutcome::Ok)
    }

    /// Compact single-line summary for logs.
    pub fn summary(&self) -> String {
        match self {
            ProbeOutcome::Ok => "ok".into(),
            ProbeOutcome::Fail { exit_code, stderr, .. } => {
                let first = stderr.lines().find(|l| l.contains("error")).unwrap_or("");
                format!("fail(exit={exit_code:?}): {first}")
            }
            ProbeOutcome::Timeout { elapsed } => {
                format!("timeout after {}s", elapsed.as_secs())
            }
        }
    }
}

/// A throwaway cargo package used to type-check a single skeleton.
pub struct DraftProbe {
    root: PathBuf,
    package_name: String,
}

impl DraftProbe {
    /// Create a new probe rooted at `<workspace_target>/cave-local-llm-drafts/<id>/`.
    ///
    /// `workspace_target` should typically be `<repo_root>/target` so the
    /// probe picks up the workspace's compilation caches.
    pub fn new(workspace_target: &Path, crate_name: &str, local_fn: &str) -> Self {
        let id = format!(
            "{}-{}-{}",
            Utc::now().format("%Y%m%d%H%M%S%3f"),
            sanitise(crate_name),
            sanitise(local_fn),
        );
        // Cargo package names must be alphanumeric + dashes/underscores.  We
        // use underscores so the dir name and package name can match exactly.
        let package_name = format!(
            "cave_draft_probe_{}_{}",
            sanitise(crate_name).replace('-', "_"),
            sanitise(local_fn).replace('-', "_"),
        );
        let root = workspace_target.join("cave-local-llm-drafts").join(id);
        Self { root, package_name }
    }

    /// Absolute path to the probe crate root.
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Materialise the probe crate on disk.  Creates `Cargo.toml` and
    /// `src/lib.rs`; the lib's only content is the candidate skeleton,
    /// wrapped in `#![allow(dead_code, unused_imports, unused_variables)]`
    /// so the probe never flags lints unrelated to correctness.
    pub fn prepare(&self, skeleton: &str) -> std::io::Result<()> {
        std::fs::create_dir_all(self.root.join("src"))?;

        let cargo_toml = format!(
            "[workspace]\n\n\
             [package]\n\
             name = \"{name}\"\n\
             version = \"0.0.0\"\n\
             edition = \"2021\"\n\
             publish = false\n\n\
             [lib]\n\
             path = \"src/lib.rs\"\n\n\
             # No dependencies: tier-1 skeletons must rely only on std / \
             primitive types.  Any `use foo::…` that escapes std will fail \
             the probe, which is exactly what we want — qwen3 regularly \
             hallucinates crates like `cave_commons` that do not exist.\n\
             [dependencies]\n",
            name = self.package_name,
        );
        std::fs::write(self.root.join("Cargo.toml"), cargo_toml)?;

        let lib_rs = format!(
            "#![allow(dead_code, unused_imports, unused_variables)]\n\
             //! Throwaway probe crate generated by cave-local-llm to type-check\n\
             //! a tier-1 skeleton before it is committed to the primary repo.\n\
             \n\
             {skeleton}\n",
            skeleton = skeleton.trim(),
        );
        std::fs::write(self.root.join("src/lib.rs"), lib_rs)?;

        Ok(())
    }

    /// Run `cargo check` on the probe with the given timeout.  Returns the
    /// outcome without propagating non-zero exits as errors — a failed
    /// compile is an expected signal, not an I/O problem.
    pub async fn check(&self, timeout: Duration) -> std::io::Result<ProbeOutcome> {
        let manifest = self.root.join("Cargo.toml");
        let start = std::time::Instant::now();

        let mut cmd = tokio::process::Command::new("cargo");
        cmd.args([
            "check",
            "--quiet",
            "--manifest-path",
        ])
        .arg(&manifest)
        // Share the host's target dir so incremental builds are fast.  This
        // places the probe's artefacts under the probe root only — they are
        // cleaned up by `DraftProbe::cleanup`.
        .env_remove("RUSTFLAGS")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

        let output = tokio::time::timeout(timeout, cmd.output()).await;
        let elapsed = start.elapsed();

        match output {
            Err(_) => Ok(ProbeOutcome::Timeout { elapsed }),
            Ok(Err(e)) => Err(e),
            Ok(Ok(out)) => {
                let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
                let stderr = String::from_utf8_lossy(&out.stderr).into_owned();
                if out.status.success() {
                    Ok(ProbeOutcome::Ok)
                } else {
                    Ok(ProbeOutcome::Fail {
                        exit_code: out.status.code(),
                        stdout,
                        stderr,
                    })
                }
            }
        }
    }

    /// Best-effort removal of the probe crate.  We keep failed probes on
    /// disk for post-mortem (they are small) — the workspace's standard
    /// `cargo clean` covers them.  Successful probes are cleaned up
    /// eagerly by the daemon.
    pub fn cleanup(&self) {
        let _ = std::fs::remove_dir_all(&self.root);
    }
}

/// Sanitise an identifier for use in a filesystem path and cargo package
/// name.  Replaces anything that is not alphanumeric/dash/underscore with
/// `_`.
fn sanitise(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_probe_new_builds_unique_ids() {
        let tmp = tempfile::tempdir().unwrap();
        let a = DraftProbe::new(tmp.path(), "cave-secrets", "scan_file");
        // Sleep so the millisecond-resolution timestamp differs.
        std::thread::sleep(Duration::from_millis(2));
        let b = DraftProbe::new(tmp.path(), "cave-secrets", "scan_file");
        assert_ne!(a.root(), b.root(), "probe roots must be unique per call");
    }

    #[test]
    fn test_probe_prepare_writes_cargo_and_lib() {
        let tmp = tempfile::tempdir().unwrap();
        let p = DraftProbe::new(tmp.path(), "cave-secrets", "scan_file");
        p.prepare("pub fn scan_file() -> bool { todo!(\"Tier 2\") }").unwrap();

        let cargo = std::fs::read_to_string(p.root().join("Cargo.toml")).unwrap();
        assert!(cargo.contains("cave_draft_probe_cave_secrets_scan_file"));
        assert!(cargo.contains("edition = \"2021\""));
        assert!(cargo.contains("[dependencies]"));
        // No actual dependencies lines — empty table.
        let deps_section_end = cargo[cargo.find("[dependencies]").unwrap()..].trim();
        assert_eq!(deps_section_end.trim(), "[dependencies]");

        let lib = std::fs::read_to_string(p.root().join("src/lib.rs")).unwrap();
        assert!(lib.contains("pub fn scan_file"));
        assert!(lib.contains("#![allow(dead_code"));
    }

    #[test]
    fn test_probe_prepare_sanitises_weird_fn_names() {
        let tmp = tempfile::tempdir().unwrap();
        let p = DraftProbe::new(tmp.path(), "cave-secrets", "some::weird path");
        p.prepare("pub fn x() {}").unwrap();
        assert!(p.root().exists(), "probe dir must materialise even with weird fn name");
        let cargo = std::fs::read_to_string(p.root().join("Cargo.toml")).unwrap();
        // Sanitised package name has all non-alphanumerics replaced with `_`.
        assert!(cargo.contains("cave_draft_probe_cave_secrets_some__weird_path"));
    }

    #[test]
    fn test_sanitise() {
        assert_eq!(sanitise("cave-secrets"), "cave-secrets");
        assert_eq!(sanitise("Scan::File"), "Scan__File");
        assert_eq!(sanitise("foo bar"), "foo_bar");
    }

    #[test]
    fn test_probe_outcome_summary_ok() {
        assert_eq!(ProbeOutcome::Ok.summary(), "ok");
    }

    #[test]
    fn test_probe_outcome_summary_fail_extracts_first_error_line() {
        let out = ProbeOutcome::Fail {
            exit_code: Some(101),
            stdout: String::new(),
            stderr: "warning: foo\nerror[E0412]: cannot find type `Secret`\n   --> src/lib.rs:3".into(),
        };
        let s = out.summary();
        assert!(s.contains("cannot find type `Secret`"), "got: {s}");
        assert!(s.contains("101"), "got: {s}");
    }

    #[test]
    fn test_probe_outcome_summary_timeout_includes_duration() {
        let out = ProbeOutcome::Timeout { elapsed: Duration::from_secs(42) };
        assert!(out.summary().contains("42"));
    }

    #[test]
    fn test_probe_outcome_is_ok() {
        assert!(ProbeOutcome::Ok.is_ok());
        assert!(!ProbeOutcome::Timeout { elapsed: Duration::from_secs(1) }.is_ok());
        assert!(!ProbeOutcome::Fail {
            exit_code: Some(1),
            stdout: String::new(),
            stderr: String::new(),
        }
        .is_ok());
    }
}
