// SPDX-License-Identifier: AGPL-3.0-or-later
//! RED tests for pulp_file PULP_MANIFEST CSV parser (Phase 2 deep-port).
//!
//! Upstream contract: `pulp_file/manifest.py` — 3-column CSV
//! `relative_path,sha256_digest,size_bytes`, blank/comment lines ignored,
//! CRLF tolerated, malformed rows raise validation errors. The render path
//! round-trips bit-for-bit.

use cave_artifacts::pulp::plugins::file::{
    parse_pulp_manifest, render_pulp_manifest, PulpManifestEntry,
};

#[test]
fn parse_pulp_manifest_three_rows_plus_comment_and_blank() {
    let body = "\
# generated by pulp_file
docs/readme.txt,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855,0

bin/tool,abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789,1024
data/big.bin,1111111111111111111111111111111111111111111111111111111111111111,1073741824
";
    let entries = parse_pulp_manifest(body).expect("valid manifest");
    assert_eq!(entries.len(), 3);
    assert_eq!(entries[0].relative_path, "docs/readme.txt");
    assert_eq!(entries[0].size, 0);
    assert_eq!(entries[1].size, 1024);
    assert_eq!(entries[2].size, 1_073_741_824);
}

#[test]
fn render_then_parse_round_trips() {
    let entries = vec![
        PulpManifestEntry {
            relative_path: "a.txt".into(),
            sha256: "00".repeat(32),
            size: 7,
        },
        PulpManifestEntry {
            relative_path: "sub/b.bin".into(),
            sha256: "ab".repeat(32),
            size: 4096,
        },
    ];
    let body = render_pulp_manifest(&entries);
    let parsed = parse_pulp_manifest(&body).unwrap();
    assert_eq!(parsed, entries);
}

#[test]
fn parse_rejects_malformed_size() {
    let body = "a.txt,abc,not-a-number\n";
    assert!(parse_pulp_manifest(body).is_err());
}

#[test]
fn parse_rejects_short_row() {
    let body = "a.txt,onlytwo\n";
    assert!(parse_pulp_manifest(body).is_err());
}

#[test]
fn parse_rejects_empty_path() {
    let body = ",abc,1\n";
    assert!(parse_pulp_manifest(body).is_err());
}

#[test]
fn parse_tolerates_crlf_and_no_trailing_newline() {
    let body = "a.txt,deadbeef00000000000000000000000000000000000000000000000000000000,7\r\nb.txt,deadbeef00000000000000000000000000000000000000000000000000000000,8";
    let entries = parse_pulp_manifest(body).unwrap();
    assert_eq!(entries.len(), 2);
    assert_eq!(entries[1].size, 8);
}
