//! Core domain types for cave-infra.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

/// Natural language or structured YAML infrastructure intent.
///
/// Example: "provision a 3-node postgres cluster in eu-west-1"
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InfraIntent {
    pub id: Uuid,
    /// Human-readable description of what is desired.
    pub description: String,
    /// Optional structured YAML representation parsed alongside the NL description.
    pub structured: Option<serde_yaml::Value>,
    /// Resolved resource declarations extracted from the intent.
    pub resources: Vec<ResourceDeclaration>,
    /// Extracted constraints (region, node count, cost limits, etc.)
    pub constraints: Vec<String>,
    pub created_at: DateTime<Utc>,
}

/// A resource declaration inside an intent (pre-resolution, pre-state-diff).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceDeclaration {
    pub name: String,
    /// Cloud provider: "aws", "azure", "gcp", "hetzner", "kubernetes".
    pub provider: String,
    /// Provider-specific resource type: "rds_cluster", "s3_bucket", "vm", etc.
    pub resource_type: String,
    pub config: HashMap<String, serde_json::Value>,
}

/// A fully tracked infrastructure resource — desired + actual state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InfraResource {
    pub id: Uuid,
    pub name: String,
    pub provider: String,
    pub resource_type: String,
    pub config: HashMap<String, serde_json::Value>,
    pub state: ResourceState,
    /// IDs of resources this resource depends on.
    pub dependencies: Vec<Uuid>,
    /// Cloud-provider assigned resource ID (e.g. "i-0abc123" for EC2).
    pub actual_id: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ResourceState {
    Pending,
    Creating,
    Active,
    Updating,
    Deleting,
    Deleted,
    Failed(String),
    Drifted,
}

/// Current vs desired state — richer than terraform.tfstate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InfraState {
    pub version: u64,
    pub resources: HashMap<Uuid, InfraResource>,
    pub last_applied: Option<DateTime<Utc>>,
    pub locked_by: Option<String>,
    pub lock_acquired_at: Option<DateTime<Utc>>,
}

impl Default for InfraState {
    fn default() -> Self {
        Self {
            version: 1,
            resources: HashMap::new(),
            last_applied: None,
            locked_by: None,
            lock_acquired_at: None,
        }
    }
}

/// An ordered, reviewable execution plan generated by the LLM planner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    pub id: Uuid,
    pub intent_id: Uuid,
    pub steps: Vec<PlanStep>,
    pub rollback_steps: Vec<PlanStep>,
    pub cost_estimate: CostEstimate,
    /// Risk score 0–100: blast radius + irreversibility.
    pub risk_score: u8,
    /// Human-readable explanation of what will happen.
    pub explanation: String,
    pub created_at: DateTime<Utc>,
    pub status: PlanStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum PlanStatus {
    Draft,
    Approved,
    Applying,
    Applied,
    Failed(String),
    RolledBack,
}

/// One atomic action in an execution plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub id: Uuid,
    pub action: StepAction,
    pub provider: String,
    pub resource_name: String,
    pub resource_type: String,
    pub params: HashMap<String, serde_json::Value>,
    /// IDs of other steps that must complete first.
    pub depends_on: Vec<Uuid>,
    pub estimated_duration_secs: u32,
    pub reversible: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum StepAction {
    Create,
    Update,
    Delete,
    NoOp,
}

/// A registered MCP server providing cloud-provider integrations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct McpProvider {
    pub id: Uuid,
    /// Logical name: "aws", "azure", "gcp", "hetzner", "kubernetes".
    pub name: String,
    /// MCP server endpoint (HTTP URL or stdio path).
    pub endpoint: String,
    pub capabilities: Vec<McpTool>,
    pub healthy: bool,
    pub registered_at: DateTime<Utc>,
}

/// A single tool exposed by an MCP server.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct McpTool {
    pub name: String,
    pub description: String,
    pub input_schema: serde_json::Value,
}

/// Detected drift between desired and actual cloud state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DriftReport {
    pub id: Uuid,
    pub detected_at: DateTime<Utc>,
    pub drifted_resources: Vec<ResourceDrift>,
    pub total_drifted: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceDrift {
    pub resource_id: Uuid,
    pub resource_name: String,
    pub field: String,
    pub desired: serde_json::Value,
    pub actual: serde_json::Value,
}

/// OPA/custom policy evaluation result before a plan is applied.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PolicyCheck {
    pub id: Uuid,
    pub policy_name: String,
    pub passed: bool,
    pub violations: Vec<String>,
    pub evaluated_at: DateTime<Utc>,
}

/// Predicted cost impact of an execution plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CostEstimate {
    pub monthly_usd: f64,
    pub hourly_usd: f64,
    pub breakdown: Vec<CostItem>,
    pub currency: String,
}

impl Default for CostEstimate {
    fn default() -> Self {
        Self {
            monthly_usd: 0.0,
            hourly_usd: 0.0,
            breakdown: Vec::new(),
            currency: "USD".to_string(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CostItem {
    pub resource_name: String,
    pub resource_type: String,
    pub monthly_usd: f64,
}
