//! Registry of tracked upstream projects.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrackedProject {
    pub name: &'static str,
    pub github_repo: &'static str,
    pub cave_module: &'static str,
    pub track_features: &'static str,
    pub check_frequency: &'static str,
}

/// All upstream projects tracked by cave-runtime.
pub const TRACKED_PROJECTS: &[TrackedProject] = &[
    TrackedProject {
        name: "Unleash",
        github_repo: "Unleash/unleash",
        cave_module: "cave-flags",
        track_features: "Feature types, strategies, metrics API, client SDK protocol",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "DefectDojo",
        github_repo: "DefectDojo/django-DefectDojo",
        cave_module: "cave-vulns",
        track_features: "Importer formats, JIRA integration patterns, finding dedup logic",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "DependencyTrack",
        github_repo: "DependencyTrack/dependency-track",
        cave_module: "cave-sbom",
        track_features: "NVD/OSV data format, CycloneDX spec, policy engine",
        check_frequency: "biweekly",
    },
    TrackedProject {
        name: "SonarQube",
        github_repo: "SonarSource/sonarqube",
        cave_module: "cave-scan",
        track_features: "New rules per language, quality profile changes, CE vs EE gap",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Pulp",
        github_repo: "pulp/pulpcore",
        cave_module: "cave-registry",
        track_features: "New repository types, content plugin API, remote sync",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Trufflehog",
        github_repo: "trufflesecurity/trufflehog",
        cave_module: "cave-secrets",
        track_features: "New detector patterns, custom detector format, verification API",
        check_frequency: "weekly",
    },
    TrackedProject {
        name: "Hadolint",
        github_repo: "hadolint/hadolint",
        cave_module: "cave-lint",
        track_features: "New Dockerfile rules, best practice changes",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Presidio",
        github_repo: "microsoft/presidio",
        cave_module: "cave-pii",
        track_features: "New recognizer patterns, language support, anonymization strategies",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Backstage",
        github_repo: "backstage/backstage",
        cave_module: "cave-portal",
        track_features: "Catalog spec, scaffolder actions, plugin API, search architecture",
        check_frequency: "weekly",
    },
    TrackedProject {
        name: "DevLake",
        github_repo: "apache/incubator-devlake",
        cave_module: "cave-devlake",
        track_features: "DORA metric calculation changes, new data source plugins",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Uptime Kuma",
        github_repo: "louislam/uptime-kuma",
        cave_module: "cave-uptime",
        track_features: "New monitor types, notification methods",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "OpenCost",
        github_repo: "opencost/opencost",
        cave_module: "cave-cost",
        track_features: "Cost model changes, cloud pricing API updates, allocation logic",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Langfuse",
        github_repo: "langfuse/langfuse",
        cave_module: "cave-ai-obs",
        track_features: "Trace schema evolution, evaluation framework, prompt management API",
        check_frequency: "biweekly",
    },
    TrackedProject {
        name: "n8n",
        github_repo: "n8n-io/n8n",
        cave_module: "cave-workflows",
        track_features: "New node types, workflow execution model, credential handling",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "LibreChat",
        github_repo: "danny-avila/LibreChat",
        cave_module: "cave-chat",
        track_features: "Provider integration patterns, conversation schema, plugin system",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Grafana OnCall",
        github_repo: "grafana/oncall",
        cave_module: "cave-incidents",
        track_features: "Escalation logic, integration methods, schedule format",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Apicurio Registry",
        github_repo: "Apicurio/apicurio-registry",
        cave_module: "cave-docs",
        track_features: "Schema format support, compatibility rules, API changes",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "cert-manager",
        github_repo: "cert-manager/cert-manager",
        cave_module: "cave-certs",
        track_features: "ACME protocol changes, new issuers, CRD evolution",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Sigstore",
        github_repo: "sigstore/cosign",
        cave_module: "cave-sign",
        track_features: "Signing formats, verification methods, SLSA spec changes",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Tetragon",
        github_repo: "cilium/tetragon",
        cave_module: "cave-forensics",
        track_features: "eBPF hook types, policy spec, export formats",
        check_frequency: "biweekly",
    },
    TrackedProject {
        name: "Chaos Mesh",
        github_repo: "chaos-mesh/chaos-mesh",
        cave_module: "cave-chaos",
        track_features: "New chaos types, schedule model, status reporting",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "OPA Gatekeeper",
        github_repo: "open-policy-agent/gatekeeper",
        cave_module: "cave-policy",
        track_features: "Constraint framework changes, audit improvements, mutation support",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Velero",
        github_repo: "vmware-tanzu/velero",
        cave_module: "cave-backup",
        track_features: "Backup/restore improvements, CSI snapshot integration, schedule model",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Teleport",
        github_repo: "gravitational/teleport",
        cave_module: "cave-pam",
        track_features: "Session recording formats, RBAC model, Kubernetes access patterns",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "Pyroscope",
        github_repo: "grafana/pyroscope",
        cave_module: "cave-profiler",
        track_features: "Profile formats, language support, eBPF profiling methods",
        check_frequency: "monthly",
    },
    TrackedProject {
        name: "ZAP",
        github_repo: "zaproxy/zaproxy",
        cave_module: "cave-dast",
        track_features: "Scan rules, API scanning, authentication methods",
        check_frequency: "monthly",
    },
];
