#!/usr/bin/env bash
# Charter v2 8-gate full-repo sweep.
# Audit only — produces a CSV-style report at docs/charter-v2-sweep.md
# Gates measured:
#   G1 source_sha pinned in parity.manifest.toml [upstream]
#   G2 SPDX header on every .rs file (AGPL-3.0-or-later)
#   G4 fill_ratio recorded in [parity]
#   G5 no unimplemented!() in src/
#   G7 same as G1 (always-latest implies the pin exists; freshness is
#      a manual cross-check against upstream HEAD)
#   G8 minimum: presence of observability.toml + cavectl wiring grep

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="docs/charter-v2-sweep.md"

{
    echo "# Charter v2 8-gate sweep — $(date -u +%Y-%m-%d)"
    echo
    echo "Auto-generated by scripts/charter-v2-sweep.sh. Per-crate gate measurements."
    echo "Gates not measurable mechanically (G3 NOTICE, G6 no-backcompat, G8 4-track full coverage) are skipped here."
    echo
    echo "Legend: ✔ pass · ✖ fail · — not applicable / not measured"
    echo
    echo "| crate | G1 source_sha | G2 SPDX | G4 fill_ratio | G5 no-stub | G8 obs/cavectl |"
    echo "|-------|---------------|---------|---------------|-----------|----------------|"
} > "$OUT"

# Cache cavectl mapping greps
CAVECTL_HITS=$(grep -roh 'cavectl [a-z-]\+' crates/cave-cli/ 2>/dev/null | sort -u || true)

bad_g1=0; bad_g2=0; bad_g4=0; bad_g5=0; bad_g8=0; total=0

for d in crates/cave-*/; do
    [ -d "$d" ] || continue
    crate=$(basename "$d")
    total=$((total + 1))
    manifest="$d/parity.manifest.toml"

    # G1 source_sha: pin required UNLESS the crate is a Cave-internal types
    # crate (infra_only = true AND no [upstream] block declared).
    if [ -f "$manifest" ] && grep -qE "source_sha\s*=" "$manifest"; then
        g1="✔"
    elif [ -f "$manifest" ] && grep -qE '^infra_only\s*=\s*true' "$manifest" \
                         && ! grep -q "^\[upstream\]" "$manifest"; then
        g1="✔ (internal)"
    else
        g1="✖"; bad_g1=$((bad_g1 + 1))
    fi

    # G2 SPDX over all .rs in this crate
    bad_spdx=0
    while IFS= read -r f; do
        first=$(head -n 1 "$f" 2>/dev/null)
        if [ "$first" != "// SPDX-License-Identifier: AGPL-3.0-or-later" ]; then
            bad_spdx=$((bad_spdx + 1))
        fi
    done < <(find "$d" -name "*.rs" -not -path "*/target/*" 2>/dev/null)
    if [ "$bad_spdx" -eq 0 ]; then g2="✔"; else g2="✖ ($bad_spdx)"; bad_g2=$((bad_g2 + 1)); fi

    # G4 fill_ratio (also accept legacy `ratio` field)
    if [ -f "$manifest" ]; then
        ratio=$(grep -E "^(fill_ratio|ratio)\s*=" "$manifest" | head -1 | awk -F'=' '{print $2}' | awk '{print $1}' | tr -d ' "')
        if [ -n "$ratio" ]; then g4="$ratio"; else g4="✖"; bad_g4=$((bad_g4 + 1)); fi
    else
        g4="—"
    fi

    # G5 no-stub: count real unimplemented!() in src/.
    # Skips: comment-only lines, string-literal occurrences, and audit-checker
    # source files (parity_self_audit.rs, stub_scan.rs, auto_port_gate.rs,
    # cave-tdd-check.rs, upstream-watchd/src/prompt.rs, portal admin meta files,
    # hermes/src/recall.rs).
    if [ -d "$d/src" ]; then
        stubs=$(grep -rEn 'unimplemented!\(' "$d/src" --include="*.rs" 2>/dev/null \
            | awk -F: 'BEGIN{n=0} {
                file=$1; line=$2;
                content="";
                for(i=3;i<=NF;i++) content = content $i (i<NF?":":"");
                if (content ~ /^[[:space:]]*\/\//) next;
                if (content ~ /^[[:space:]]*\*/) next;
                if (content ~ /"[^"]*unimplemented!/) next;
                if (file ~ /parity_self_audit\.rs$/) next;
                if (file ~ /stub_scan\.rs$/) next;
                if (file ~ /auto_port_gate\.rs$/) next;
                if (file ~ /cave-tdd-check\.rs$/) next;
                if (file ~ /upstream-watchd.*prompt\.rs$/) next;
                if (file ~ /portal.*compliance\.rs$/) next;
                if (file ~ /portal.*meta_audit\.rs$/) next;
                if (file ~ /hermes.*recall\.rs$/) next;
                n++
            } END{print n}')
        if [ "$stubs" -eq 0 ]; then g5="✔"; else g5="✖ ($stubs)"; bad_g5=$((bad_g5 + 1)); fi
    else
        g5="—"
    fi

    # G8 obs + cavectl
    obs_present="—"
    if [ -f "$d/observability.toml" ] || [ -f "$d/observability/dashboard.json" ]; then
        obs_present="obs✔"
    fi
    # Strip 'cave-' prefix for cavectl subcommand match
    sub=${crate#cave-}
    cavectl_present="—"
    if echo "$CAVECTL_HITS" | grep -q "cavectl $sub"; then
        cavectl_present="cli✔"
    fi
    g8="$obs_present $cavectl_present"
    if [ "$obs_present" = "—" ] && [ "$cavectl_present" = "—" ]; then bad_g8=$((bad_g8 + 1)); fi

    echo "| $crate | $g1 | $g2 | $g4 | $g5 | $g8 |" >> "$OUT"
done

{
    echo
    echo "## Summary"
    echo
    echo "- Total crates audited: $total"
    echo "- G1 source_sha missing: $bad_g1"
    echo "- G2 SPDX bad: $bad_g2"
    echo "- G4 fill_ratio missing: $bad_g4"
    echo "- G5 stubs present: $bad_g5"
    echo "- G8 neither obs nor cavectl: $bad_g8"
} >> "$OUT"

echo "Wrote $OUT"
echo "total=$total g1_bad=$bad_g1 g2_bad=$bad_g2 g4_bad=$bad_g4 g5_bad=$bad_g5 g8_bad=$bad_g8"
