#!/usr/bin/env bash
# oss-hijyen-prep.sh — pre-OSS-launch hygiene inventory
# See docs/adr/ADR-148_OSS_Launch_History_Strategy.md
#
# Usage:
#   bash scripts/oss-hijyen-prep.sh                 # dry-run, default report path
#   bash scripts/oss-hijyen-prep.sh --output PATH   # dry-run, custom report
#   bash scripts/oss-hijyen-prep.sh --strict        # exit 1 if any leak found
#
# This script does NOT modify files. It produces a markdown report listing
# leak candidates so Faz 1 hygiene sprint (2026-05-14) can scrub them.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

DATE=$(date +%Y-%m-%d)
OUTPUT="docs/oss-prep/hijyen-report-${DATE}.md"
STRICT=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT="$2"; shift 2 ;;
    --strict) STRICT=1; shift ;;
    --help|-h)
      sed -n '2,11p' "$0"
      exit 0
      ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT")"

# Counters for the strict-mode gate.
TOTAL_LEAKS=0

# Helper: append a section to the report.
section() { printf '\n## %s\n\n' "$1" >> "$OUTPUT"; }
note()    { printf '%s\n' "$1" >> "$OUTPUT"; }
code()    { printf '```\n%s\n```\n' "$1" >> "$OUTPUT"; }

# ── Header ──────────────────────────────────────────────────────────────────
cat > "$OUTPUT" <<EOF
# OSS Hijyen Report — ${DATE}

Generated by \`scripts/oss-hijyen-prep.sh\` (dry-run; no files modified).
See ADR-148 for the launch strategy this report feeds.

EOF

# ── 1. Secret scanners (best-effort; skip with note if not installed) ──────
section "1. Secret scanners"

if command -v trufflehog >/dev/null 2>&1; then
  note "**trufflehog** found at \`$(command -v trufflehog)\` — running filesystem scan…"
  TH_OUT=$(trufflehog filesystem --no-update --json "$REPO_ROOT" 2>/dev/null | wc -l | tr -d ' ')
  note "trufflehog hits: **${TH_OUT}** raw lines (each line is one finding)."
  TOTAL_LEAKS=$((TOTAL_LEAKS + TH_OUT))
else
  note "⚠️ \`trufflehog\` not installed — skipping. Install with \`brew install trufflehog\` before Faz 1 sprint."
fi

if command -v gitleaks >/dev/null 2>&1; then
  note ""
  note "**gitleaks** found at \`$(command -v gitleaks)\` — running working-tree scan…"
  GL_OUT=$(gitleaks detect --no-git --no-banner --redact --report-format=json --report-path=/dev/stderr 2>&1 1>/dev/null | grep -c '"RuleID"' || true)
  note "gitleaks hits: **${GL_OUT}** findings (working-tree only; history scan would need \`detect\` without \`--no-git\`)."
  TOTAL_LEAKS=$((TOTAL_LEAKS + GL_OUT))
else
  note ""
  note "⚠️ \`gitleaks\` not installed — skipping. Install with \`brew install gitleaks\` before Faz 1 sprint."
fi

# ── 2. .DS_Store ────────────────────────────────────────────────────────────
section "2. .DS_Store files"

DS_COUNT=$(find . -path ./target -prune -o -path ./node_modules -prune -o -name '.DS_Store' -print 2>/dev/null | grep -c '.DS_Store' || true)
note "Found **${DS_COUNT}** \`.DS_Store\` files."
if [[ $DS_COUNT -gt 0 ]]; then
  note ""
  note "Sample (first 10):"
  printf '```\n' >> "$OUTPUT"
  find . -path ./target -prune -o -path ./node_modules -prune -o -name '.DS_Store' -print 2>/dev/null | head -10 >> "$OUTPUT"
  printf '```\n' >> "$OUTPUT"
  note ""
  note "**Faz 1 fix:** \`find . -name '.DS_Store' -delete\`"
  TOTAL_LEAKS=$((TOTAL_LEAKS + DS_COUNT))
fi

# ── 3. Build artefact directories that should not be committed ──────────────
section "3. Build artefact directories (should be gitignore'd)"

BUILD_HITS=0
for dir in target node_modules dist .cache .next build; do
  if git ls-files "$dir" 2>/dev/null | head -1 | grep -q .; then
    cnt=$(git ls-files "$dir" 2>/dev/null | wc -l | tr -d ' ')
    note "⚠️ \`$dir/\` has **${cnt}** tracked files. Should be in \`.gitignore\`."
    BUILD_HITS=$((BUILD_HITS + cnt))
  fi
done
if [[ $BUILD_HITS -eq 0 ]]; then
  note "✓ No build artefacts tracked in git."
else
  TOTAL_LEAKS=$((TOTAL_LEAKS + BUILD_HITS))
fi

# ── 4. Path leakage — /Users/gnomish/ ───────────────────────────────────────
section "4. Path leakage — \`/Users/gnomish/\`"

# Scope: source + docs + scripts + configs. Skip target/, node_modules/, .git/.
PATH_HITS=$(rg -l '/Users/gnomish' \
  --glob '!target/**' \
  --glob '!node_modules/**' \
  --glob '!.git/**' \
  --glob '!.claude/worktrees/**' \
  2>/dev/null | wc -l | tr -d ' ')

note "Files containing \`/Users/gnomish\`: **${PATH_HITS}**"

if [[ $PATH_HITS -gt 0 ]]; then
  note ""
  note "Top 30 by file (path → line count):"
  printf '```\n' >> "$OUTPUT"
  rg -c '/Users/gnomish' \
    --glob '!target/**' \
    --glob '!node_modules/**' \
    --glob '!.git/**' \
    --glob '!.claude/worktrees/**' \
    2>/dev/null \
    | sort -t: -k2 -rn | head -30 >> "$OUTPUT"
  printf '```\n' >> "$OUTPUT"
  note ""
  note "**Faz 1 fix:** sed-replace with \`\$HOME\` or \`~/\`. Audit each hit — some are example paths in docs which is fine; others are baked-in plist / launchctl paths that need env-var indirection."
  TOTAL_LEAKS=$((TOTAL_LEAKS + PATH_HITS))
fi

# ── 5. Email leakage — btartan@gmail.com + other personal emails ───────────
section "5. Email leakage"

EMAIL_HITS=$(rg -l 'btartan@gmail\.com' \
  --glob '!target/**' \
  --glob '!.git/**' \
  --glob '!.claude/worktrees/**' \
  2>/dev/null | wc -l | tr -d ' ')

note "Files containing \`btartan@gmail.com\`: **${EMAIL_HITS}**"

if [[ $EMAIL_HITS -gt 0 ]]; then
  note ""
  note "All hits:"
  printf '```\n' >> "$OUTPUT"
  rg -c 'btartan@gmail\.com' \
    --glob '!target/**' \
    --glob '!.git/**' \
    --glob '!.claude/worktrees/**' \
    2>/dev/null | head -30 >> "$OUTPUT"
  printf '```\n' >> "$OUTPUT"
  TOTAL_LEAKS=$((TOTAL_LEAKS + EMAIL_HITS))
fi

# Catch-all for any email-shaped string in source / docs (not exhaustive — sample only)
note ""
note "Other emails in working tree (sample, top 30 distinct):"
printf '```\n' >> "$OUTPUT"
rg -oI '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}' \
  --glob '!target/**' \
  --glob '!.git/**' \
  --glob '!.claude/worktrees/**' \
  2>/dev/null \
  | sort -u | grep -vE 'noreply@|@example\.|@cave-runtime|@anthropic\.com$' | head -30 >> "$OUTPUT" || true
printf '```\n' >> "$OUTPUT"
note ""
note "**Faz 1 fix:** decide per-file: replace personal with \`noreply@cave-runtime.org\` placeholder, or mark intentional (third-party in docs)."

# ── 6. Co-Authored-By trailers in commit history (informational) ────────────
section "6. Commit history Co-Authored-By trailers (informational only)"

note "Orphan-launch (ADR-148) discards commit history; this section is for **CREDITS.md** input, not for scrubbing."
note ""

git log --pretty=%B 2>/dev/null \
  | grep -oE 'Co-Authored-By:[^<]*<[^>]+>' \
  | sort | uniq -c | sort -rn | head -20 \
  > /tmp/oss-coauth.txt 2>/dev/null

if [[ -s /tmp/oss-coauth.txt ]]; then
  note "Top Co-Authored-By trailers (count → trailer):"
  printf '```\n' >> "$OUTPUT"
  cat /tmp/oss-coauth.txt >> "$OUTPUT"
  printf '```\n' >> "$OUTPUT"
fi
rm -f /tmp/oss-coauth.txt

# ── 7. Compliance files presence check ──────────────────────────────────────
section "7. Compliance / OSS launch required files"

MISSING=0
for f in LICENSE NOTICE README.md CREDITS.md CONTRIBUTING.md CODE_OF_CONDUCT.md SECURITY.md docs/HISTORY.md; do
  if [[ -f "$f" ]]; then
    note "- ✓ \`$f\` exists"
  else
    note "- ✗ \`$f\` **missing**"
    MISSING=$((MISSING + 1))
  fi
done
if [[ $MISSING -gt 0 ]]; then
  note ""
  note "**Faz 1 fix:** create the missing files before launch. ADR-148 verification gate #4 requires all of them."
  TOTAL_LEAKS=$((TOTAL_LEAKS + MISSING))
fi

# ── 8. Cargo.toml license + repository sanity ───────────────────────────────
section "8. Cargo.toml license / repository fields"

NO_LICENSE=$(rg -L '^license\s*=' --glob 'crates/*/Cargo.toml' 2>/dev/null | wc -l | tr -d ' ')
WORKSPACE_LICENSE=$(rg -l '^license\.workspace\s*=\s*true' --glob 'crates/*/Cargo.toml' 2>/dev/null | wc -l | tr -d ' ')
NO_REPO=$(rg -L '^(repository|repository\.workspace)' --glob 'crates/*/Cargo.toml' 2>/dev/null | wc -l | tr -d ' ')

note "- crates without explicit \`license =\` line (may inherit from workspace): ${NO_LICENSE}"
note "- crates with \`license.workspace = true\`: ${WORKSPACE_LICENSE}"
note "- crates without \`repository\` reference: ${NO_REPO}"
note ""
note "**Faz 1 fix:** confirm root \`Cargo.toml\` has \`[workspace.package] license = \"Apache-2.0\" repository = \"…\"\`; nudge stragglers to inherit."

# ── 9. Summary ──────────────────────────────────────────────────────────────
section "Summary"

note "**Total leak-candidate count:** ${TOTAL_LEAKS}"
note ""
note "Breakdown:"
note "- .DS_Store files: ${DS_COUNT}"
note "- Build artefacts tracked: ${BUILD_HITS}"
note "- Files with \`/Users/gnomish\`: ${PATH_HITS}"
note "- Files with \`btartan@gmail.com\`: ${EMAIL_HITS}"
note "- Compliance files missing: ${MISSING}"
note ""
note "Per ADR-148, none of these block the orphan-launch strategy on the *history* side, but **all of them must be fixed in the working tree** during the Faz 1 hygiene sprint (2026-05-14 → 2026-05-19) before the launch commit is taken."

echo "report → $OUTPUT"
echo "total leak-candidate count: $TOTAL_LEAKS"

if [[ $STRICT -eq 1 && $TOTAL_LEAKS -gt 0 ]]; then
  exit 1
fi
exit 0
