// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2026 Cave Runtime contributors
//! Per-tenant control-plane certificate lifecycle — the cave port of
//! Kamaji's certificate controller surface.
//!
//! Upstream reference (clastix/kamaji v1.0.0):
//!   internal/kubeadm/certificates.go            (PKI tree + base names)
//!   internal/resources/ca_certificate.go        (CA generation)
//!   internal/resources/api_server_certificate.go (apiserver serving cert + SANs)
//!   internal/resources/{api_server_kubelet_client,front-proxy-client,sa}_certificate.go
//!   controllers/certificate_lifecycle_controller.go (rotation deadline)
//!
//! Kamaji generates a full kubeadm-shaped PKI per TenantControlPlane —
//! a Kubernetes root CA, a front-proxy CA, leaf serving/client certs, and
//! the service-account key-pair — then runs a `CertificateLifecycle`
//! controller that rotates any cert (bare x509 secret or kubeconfig-embedded
//! client cert) once it falls inside a one-day expiry deadline.
//!
//! Real x509 signing is delegated to cave-certs / cave-pki (this workspace's
//! crypto owners); this module ports the *decision* layer that upstream owns:
//! the kubeadm PKI tree (who signs whom), the apiserver SAN computation, the
//! rotation deadline, and the regeneration-skip predicate.

/// A kubeadm certificate base name in the per-tenant PKI.
///
/// Mirrors the `getKubeadmCert` switch in upstream
/// `internal/kubeadm/certificates.go`, plus the service-account key-pair
/// generated by `GeneratePublicKeyPrivateKeyPair`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CertBaseName {
    /// Kubernetes root CA (`ca`).
    Ca,
    /// kube-apiserver serving certificate (`apiserver`).
    ApiServer,
    /// kube-apiserver → kubelet client certificate (`apiserver-kubelet-client`).
    ApiServerKubeletClient,
    /// Front-proxy CA (`front-proxy-ca`).
    FrontProxyCa,
    /// Aggregation-layer front-proxy client certificate (`front-proxy-client`).
    FrontProxyClient,
    /// Service-account signing key-pair (`sa`) — a key-pair, not an x509 cert.
    Sa,
}

/// Leaf extended-key-usage role, matching the `x509.ExtKeyUsage*` values the
/// upstream `crypto.VerifyCertificate` calls assert per resource.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExtKeyUsage {
    /// TLS server (kube-apiserver serving cert).
    ServerAuth,
    /// TLS client (kubelet-client / front-proxy-client).
    ClientAuth,
}

impl CertBaseName {
    /// The kubeadm on-disk base name (matches `kubeadmconstants.*BaseName`).
    pub fn base_name(&self) -> &'static str {
        match self {
            CertBaseName::Ca => "ca",
            CertBaseName::ApiServer => "apiserver",
            CertBaseName::ApiServerKubeletClient => "apiserver-kubelet-client",
            CertBaseName::FrontProxyCa => "front-proxy-ca",
            CertBaseName::FrontProxyClient => "front-proxy-client",
            CertBaseName::Sa => "sa",
        }
    }

    /// True for the two certificate authorities (generated via `CreateAsCA`).
    pub fn is_ca(&self) -> bool {
        matches!(self, CertBaseName::Ca | CertBaseName::FrontProxyCa)
    }

    /// True for the service-account material, which upstream emits as a bare
    /// public/private key-pair (`GeneratePublicKeyPrivateKeyPair`) rather than
    /// a signed x509 certificate.
    pub fn is_keypair(&self) -> bool {
        matches!(self, CertBaseName::Sa)
    }

    /// The CA that signs this subject, or `None` for a self-signed CA / the
    /// SA key-pair. Mirrors `CreateFromCA` vs `CreateAsCA` in upstream.
    pub fn signer(&self) -> Option<CertBaseName> {
        match self {
            CertBaseName::ApiServer | CertBaseName::ApiServerKubeletClient => Some(CertBaseName::Ca),
            CertBaseName::FrontProxyClient => Some(CertBaseName::FrontProxyCa),
            CertBaseName::Ca | CertBaseName::FrontProxyCa | CertBaseName::Sa => None,
        }
    }

    /// The leaf extended-key-usage, or `None` for CAs and the SA key-pair.
    pub fn ext_key_usage(&self) -> Option<ExtKeyUsage> {
        match self {
            CertBaseName::ApiServer => Some(ExtKeyUsage::ServerAuth),
            CertBaseName::ApiServerKubeletClient | CertBaseName::FrontProxyClient => {
                Some(ExtKeyUsage::ClientAuth)
            }
            CertBaseName::Ca | CertBaseName::FrontProxyCa | CertBaseName::Sa => None,
        }
    }
}

/// The full per-tenant PKI tree in generation order — every CA precedes the
/// leaves it signs, so a single forward pass can build the whole chain.
pub fn pki_tree() -> Vec<CertBaseName> {
    vec![
        CertBaseName::Ca,
        CertBaseName::ApiServer,
        CertBaseName::ApiServerKubeletClient,
        CertBaseName::FrontProxyCa,
        CertBaseName::FrontProxyClient,
        CertBaseName::Sa,
    ]
}

/// Subject-alternative-name set for a serving certificate, split into DNS
/// names and IP addresses the way kubeadm's `certutil.AltNames` is.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AltNames {
    pub dns_names: Vec<String>,
    pub ip_addresses: Vec<String>,
}

impl AltNames {
    /// Append a SAN, routing it to `ip_addresses` when it parses as an IP and
    /// to `dns_names` otherwise. Duplicates (in either bucket) are dropped so
    /// the cert carries each name once.
    fn push(&mut self, value: &str) {
        if value.is_empty() {
            return;
        }
        if value.parse::<std::net::IpAddr>().is_ok() {
            if !self.ip_addresses.iter().any(|v| v == value) {
                self.ip_addresses.push(value.to_string());
            }
        } else if !self.dns_names.iter().any(|v| v == value) {
            self.dns_names.push(value.to_string());
        }
    }
}

/// Compute the kube-apiserver serving-cert SANs for a tenant control plane,
/// mirroring kubeadm's `GetAPIServerAltNames`:
///
///   * the four standard `kubernetes[.default[.svc[.<dns_domain>]]]` DNS names,
///   * the in-cluster apiserver service IP and the loopback address,
///   * the control-plane endpoint (routed to DNS or IP by parse), and
///   * any operator-supplied extra cert-SANs (also DNS/IP routed).
///
/// All entries are de-duplicated, preserving first-seen order.
pub fn apiserver_cert_sans(
    service_dns_domain: &str,
    service_ip: &str,
    control_plane_endpoint: Option<&str>,
    extra_sans: &[String],
) -> AltNames {
    let mut names = AltNames::default();
    // Standard kubeadm DNS names.
    names.push("kubernetes");
    names.push("kubernetes.default");
    names.push("kubernetes.default.svc");
    names.push(&format!("kubernetes.default.svc.{service_dns_domain}"));
    // In-cluster service IP + loopback.
    names.push(service_ip);
    names.push("127.0.0.1");
    // Control-plane endpoint, routed by DNS-vs-IP parse.
    if let Some(ep) = control_plane_endpoint {
        names.push(ep);
    }
    // Operator-supplied extras.
    for san in extra_sans {
        names.push(san);
    }
    names
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Cycle 1: PKI tree ───────────────────────────────────────────────────

    #[test]
    fn base_names_match_kubeadm_constants() {
        assert_eq!(CertBaseName::Ca.base_name(), "ca");
        assert_eq!(CertBaseName::ApiServer.base_name(), "apiserver");
        assert_eq!(
            CertBaseName::ApiServerKubeletClient.base_name(),
            "apiserver-kubelet-client"
        );
        assert_eq!(CertBaseName::FrontProxyCa.base_name(), "front-proxy-ca");
        assert_eq!(
            CertBaseName::FrontProxyClient.base_name(),
            "front-proxy-client"
        );
        assert_eq!(CertBaseName::Sa.base_name(), "sa");
    }

    #[test]
    fn cas_are_self_signed_leaves_chain_to_their_ca() {
        // CAs sign themselves (no parent signer).
        assert_eq!(CertBaseName::Ca.signer(), None);
        assert_eq!(CertBaseName::FrontProxyCa.signer(), None);
        // Kubernetes leaves chain to the root CA.
        assert_eq!(CertBaseName::ApiServer.signer(), Some(CertBaseName::Ca));
        assert_eq!(
            CertBaseName::ApiServerKubeletClient.signer(),
            Some(CertBaseName::Ca)
        );
        // Front-proxy client chains to the front-proxy CA.
        assert_eq!(
            CertBaseName::FrontProxyClient.signer(),
            Some(CertBaseName::FrontProxyCa)
        );
    }

    #[test]
    fn is_ca_and_is_keypair_classify_correctly() {
        assert!(CertBaseName::Ca.is_ca());
        assert!(CertBaseName::FrontProxyCa.is_ca());
        assert!(!CertBaseName::ApiServer.is_ca());
        // The service-account material is a bare key-pair, not an x509 cert.
        assert!(CertBaseName::Sa.is_keypair());
        assert!(!CertBaseName::Ca.is_keypair());
    }

    #[test]
    fn ext_key_usage_follows_server_vs_client_role() {
        assert_eq!(
            CertBaseName::ApiServer.ext_key_usage(),
            Some(ExtKeyUsage::ServerAuth)
        );
        assert_eq!(
            CertBaseName::ApiServerKubeletClient.ext_key_usage(),
            Some(ExtKeyUsage::ClientAuth)
        );
        assert_eq!(
            CertBaseName::FrontProxyClient.ext_key_usage(),
            Some(ExtKeyUsage::ClientAuth)
        );
        // CAs and the SA key-pair carry no leaf ext-key-usage.
        assert_eq!(CertBaseName::Ca.ext_key_usage(), None);
        assert_eq!(CertBaseName::Sa.ext_key_usage(), None);
    }

    #[test]
    fn pki_tree_lists_every_subject_cas_before_their_leaves() {
        let tree = pki_tree();
        assert_eq!(tree.len(), 6);
        // Each non-CA, non-keypair leaf's signer must appear earlier in the tree.
        for (i, cert) in tree.iter().enumerate() {
            if let Some(signer) = cert.signer() {
                let signer_idx = tree.iter().position(|c| *c == signer).unwrap();
                assert!(
                    signer_idx < i,
                    "{:?} must be generated after its signer {:?}",
                    cert,
                    signer
                );
            }
        }
    }

    // ── Cycle 2: apiserver SANs ─────────────────────────────────────────────

    #[test]
    fn apiserver_sans_include_the_standard_kubernetes_dns_names() {
        let san = apiserver_cert_sans("cluster.local", "10.96.0.1", None, &[]);
        assert_eq!(
            san.dns_names,
            vec![
                "kubernetes",
                "kubernetes.default",
                "kubernetes.default.svc",
                "kubernetes.default.svc.cluster.local",
            ]
        );
    }

    #[test]
    fn apiserver_sans_include_service_ip_and_loopback() {
        let san = apiserver_cert_sans("cluster.local", "10.96.0.1", None, &[]);
        assert_eq!(san.ip_addresses, vec!["10.96.0.1", "127.0.0.1"]);
    }

    #[test]
    fn apiserver_sans_route_endpoint_by_dns_vs_ip() {
        // A DNS control-plane endpoint lands in dns_names.
        let dns = apiserver_cert_sans("cluster.local", "10.96.0.1", Some("cp.example.com"), &[]);
        assert!(dns.dns_names.contains(&"cp.example.com".to_string()));
        assert!(!dns.ip_addresses.contains(&"cp.example.com".to_string()));

        // An IP control-plane endpoint lands in ip_addresses.
        let ip = apiserver_cert_sans("cluster.local", "10.96.0.1", Some("203.0.113.7"), &[]);
        assert!(ip.ip_addresses.contains(&"203.0.113.7".to_string()));
        assert!(!ip.dns_names.contains(&"203.0.113.7".to_string()));
    }

    #[test]
    fn apiserver_sans_append_extra_certsans_split_and_deduped() {
        let extra = vec![
            "tenant.internal".to_string(),
            "192.168.1.10".to_string(),
            // duplicates of standard entries must not appear twice
            "kubernetes".to_string(),
            "127.0.0.1".to_string(),
        ];
        let san = apiserver_cert_sans("cluster.local", "10.96.0.1", None, &extra);
        // "kubernetes" appears exactly once.
        assert_eq!(
            san.dns_names.iter().filter(|n| *n == "kubernetes").count(),
            1
        );
        assert_eq!(
            san.ip_addresses.iter().filter(|n| *n == "127.0.0.1").count(),
            1
        );
        // extra DNS + IP entries are present.
        assert!(san.dns_names.contains(&"tenant.internal".to_string()));
        assert!(san.ip_addresses.contains(&"192.168.1.10".to_string()));
    }
}
