//! SOC2 Type II and ISO 27001 control catalogs with cross-framework mappings.

use crate::models::{Control, ControlMapping, EvidenceType, Framework};
use chrono::Utc;

// ─── SOC2 Type II Controls ───────────────────────────────────────────────────

pub fn soc2_controls() -> Vec<Control> {
    let now = Utc::now();
    vec![
        Control {
            id: "CC1.1".into(),
            title: "COSO Principle 1: Commitment to Integrity and Ethical Values".into(),
            description: "The entity demonstrates a commitment to integrity and ethical values.".into(),
            framework: Framework::Soc2TypeII,
            category: "Control Environment".into(),
            implementation_guidance: "Establish a code of conduct, communicate it to all personnel, and monitor adherence.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::AuditLog],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.5.1.1".into() }],
            created_at: now,
        },
        Control {
            id: "CC2.1".into(),
            title: "COSO Principle 6: Board Oversight of Internal Control".into(),
            description: "The board of directors demonstrates independence from management and exercises oversight of the development and performance of internal control.".into(),
            framework: Framework::Soc2TypeII,
            category: "Communication and Information".into(),
            implementation_guidance: "Establish board oversight committees, conduct regular board reviews of security posture.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::AuditLog],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.6.1.1".into() }],
            created_at: now,
        },
        Control {
            id: "CC3.1".into(),
            title: "COSO Principle 7: Establish Organizational Structure".into(),
            description: "Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in pursuit of objectives.".into(),
            framework: Framework::Soc2TypeII,
            category: "Risk Assessment".into(),
            implementation_guidance: "Define organizational chart, roles, and responsibilities for security functions.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.6.1.1".into() }],
            created_at: now,
        },
        Control {
            id: "CC4.1".into(),
            title: "COSO Principle 10: Select and Develop Control Activities".into(),
            description: "The entity selects and develops control activities that contribute to the mitigation of risks to the achievement of objectives.".into(),
            framework: Framework::Soc2TypeII,
            category: "Monitoring Activities".into(),
            implementation_guidance: "Identify and document controls, assign owners, and establish monitoring cadence.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::SecurityAssessment],
            mappings: vec![],
            created_at: now,
        },
        Control {
            id: "CC5.1".into(),
            title: "COSO Principle 11: Select and Develop Technology Controls".into(),
            description: "The entity selects and develops general control activities over technology to support the achievement of objectives.".into(),
            framework: Framework::Soc2TypeII,
            category: "Control Activities".into(),
            implementation_guidance: "Implement technology controls including automated monitoring, alerting, and access controls.".into(),
            evidence_types: vec![EvidenceType::ConfigSnapshot, EvidenceType::ScanResult],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.12.1.1".into() }],
            created_at: now,
        },
        Control {
            id: "CC6.1".into(),
            title: "Logical and Physical Access Controls".into(),
            description: "The entity implements logical access security software, infrastructure, and architectures over protected information assets.".into(),
            framework: Framework::Soc2TypeII,
            category: "Logical and Physical Access Controls".into(),
            implementation_guidance: "Implement MFA, role-based access control, privileged access management, and physical security controls.".into(),
            evidence_types: vec![EvidenceType::AccessLog, EvidenceType::ConfigSnapshot],
            mappings: vec![
                ControlMapping { framework: Framework::Iso27001, control_id: "A.9.1.1".into() },
                ControlMapping { framework: Framework::Iso27001, control_id: "A.9.4.1".into() },
            ],
            created_at: now,
        },
        Control {
            id: "CC6.2".into(),
            title: "Prior to Issuing System Credentials, Review Access".into(),
            description: "Prior to issuing system credentials and granting system access, the entity registers and authorizes new internal and external users.".into(),
            framework: Framework::Soc2TypeII,
            category: "Logical and Physical Access Controls".into(),
            implementation_guidance: "Implement an access request and approval workflow; verify identity before provisioning credentials.".into(),
            evidence_types: vec![EvidenceType::AccessLog, EvidenceType::AuditLog],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.9.2.1".into() }],
            created_at: now,
        },
        Control {
            id: "CC6.3".into(),
            title: "Role-Based Access Control".into(),
            description: "The entity authorizes, modifies, or removes access to data, software, functions, and other protected information assets based on roles and responsibilities.".into(),
            framework: Framework::Soc2TypeII,
            category: "Logical and Physical Access Controls".into(),
            implementation_guidance: "Define roles with least-privilege principles, implement RBAC, review access quarterly.".into(),
            evidence_types: vec![EvidenceType::AccessLog, EvidenceType::ConfigSnapshot],
            mappings: vec![
                ControlMapping { framework: Framework::Iso27001, control_id: "A.9.2.1".into() },
                ControlMapping { framework: Framework::Iso27001, control_id: "A.9.4.1".into() },
            ],
            created_at: now,
        },
        Control {
            id: "CC7.1".into(),
            title: "Monitoring of System Components".into(),
            description: "The entity uses detection and monitoring procedures to identify changes to configurations or new vulnerabilities.".into(),
            framework: Framework::Soc2TypeII,
            category: "System Operations".into(),
            implementation_guidance: "Deploy centralized logging, SIEM, and vulnerability scanning with alerting on anomalies.".into(),
            evidence_types: vec![EvidenceType::ScanResult, EvidenceType::AuditLog, EvidenceType::ConfigSnapshot],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.12.6.1".into() }],
            created_at: now,
        },
        Control {
            id: "CC7.2".into(),
            title: "System Anomaly Detection".into(),
            description: "The entity monitors system components and the operation of those components for anomalies that are indicative of malicious acts.".into(),
            framework: Framework::Soc2TypeII,
            category: "System Operations".into(),
            implementation_guidance: "Implement IDS/IPS, behavioral analytics, and automated threat detection.".into(),
            evidence_types: vec![EvidenceType::ScanResult, EvidenceType::SecurityAssessment],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.16.1.1".into() }],
            created_at: now,
        },
        Control {
            id: "CC8.1".into(),
            title: "Change Management Process".into(),
            description: "The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures.".into(),
            framework: Framework::Soc2TypeII,
            category: "Change Management".into(),
            implementation_guidance: "Implement formal change management process with approvals, testing, and rollback procedures.".into(),
            evidence_types: vec![EvidenceType::AuditLog, EvidenceType::PolicyDocument],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.14.2.1".into() }],
            created_at: now,
        },
        Control {
            id: "CC9.1".into(),
            title: "Risk Assessment and Mitigation".into(),
            description: "The entity identifies, selects, and develops risk mitigation activities for risks arising from potential business disruptions.".into(),
            framework: Framework::Soc2TypeII,
            category: "Risk Mitigation".into(),
            implementation_guidance: "Conduct regular risk assessments, maintain risk register, and implement mitigation controls.".into(),
            evidence_types: vec![EvidenceType::SecurityAssessment, EvidenceType::PolicyDocument],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.18.1.1".into() }],
            created_at: now,
        },
        Control {
            id: "A1.1".into(),
            title: "Availability: Performance Monitoring".into(),
            description: "The entity maintains, monitors, and evaluates current processing capacity and use to manage capacity demand.".into(),
            framework: Framework::Soc2TypeII,
            category: "Availability".into(),
            implementation_guidance: "Implement capacity monitoring, alerting on thresholds, and auto-scaling policies.".into(),
            evidence_types: vec![EvidenceType::ConfigSnapshot, EvidenceType::AuditLog],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.17.1.1".into() }],
            created_at: now,
        },
        Control {
            id: "A1.2".into(),
            title: "Availability: Recovery Testing".into(),
            description: "The entity authorizes, designs, develops or acquires, implements, operates, approves, maintains, and monitors environmental protections, software, data backup processes, and recovery infrastructure.".into(),
            framework: Framework::Soc2TypeII,
            category: "Availability".into(),
            implementation_guidance: "Conduct regular DR tests, document RTO/RPO objectives, test backup restoration.".into(),
            evidence_types: vec![EvidenceType::AuditLog, EvidenceType::SecurityAssessment],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.17.1.1".into() }],
            created_at: now,
        },
        Control {
            id: "C1.1".into(),
            title: "Confidentiality Controls".into(),
            description: "The entity identifies and maintains confidential information to meet the entity's objectives related to confidentiality.".into(),
            framework: Framework::Soc2TypeII,
            category: "Confidentiality".into(),
            implementation_guidance: "Classify data by sensitivity, implement encryption at rest and in transit, restrict access.".into(),
            evidence_types: vec![EvidenceType::ConfigSnapshot, EvidenceType::PolicyDocument, EvidenceType::AccessLog],
            mappings: vec![ControlMapping { framework: Framework::Iso27001, control_id: "A.10.1.1".into() }],
            created_at: now,
        },
    ]
}

// ─── ISO 27001 Controls ───────────────────────────────────────────────────────

pub fn iso27001_controls() -> Vec<Control> {
    let now = Utc::now();
    vec![
        Control {
            id: "A.5.1.1".into(),
            title: "Information Security Policies".into(),
            description: "A set of policies for information security shall be defined, approved by management, published and communicated to employees and relevant external parties.".into(),
            framework: Framework::Iso27001,
            category: "Information Security Policies".into(),
            implementation_guidance: "Define and document an information security policy; obtain management approval and communicate to all staff.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument],
            mappings: vec![ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC1.1".into() }],
            created_at: now,
        },
        Control {
            id: "A.6.1.1".into(),
            title: "Information Security Roles and Responsibilities".into(),
            description: "All information security responsibilities shall be defined and allocated.".into(),
            framework: Framework::Iso27001,
            category: "Organization of Information Security".into(),
            implementation_guidance: "Document RACI matrix for security roles; assign a CISO or equivalent; define security responsibilities in job descriptions.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument],
            mappings: vec![
                ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC2.1".into() },
                ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC3.1".into() },
            ],
            created_at: now,
        },
        Control {
            id: "A.8.1.1".into(),
            title: "Inventory of Assets".into(),
            description: "Assets associated with information and information processing facilities shall be identified and an inventory of these assets shall be drawn up and maintained.".into(),
            framework: Framework::Iso27001,
            category: "Asset Management".into(),
            implementation_guidance: "Maintain an up-to-date asset inventory including hardware, software, data, and services.".into(),
            evidence_types: vec![EvidenceType::ConfigSnapshot, EvidenceType::AuditLog],
            mappings: vec![],
            created_at: now,
        },
        Control {
            id: "A.9.1.1".into(),
            title: "Access Control Policy".into(),
            description: "An access control policy shall be established, documented and reviewed based on business and information security requirements.".into(),
            framework: Framework::Iso27001,
            category: "Access Control".into(),
            implementation_guidance: "Define and document an access control policy covering least privilege, need-to-know, and segregation of duties.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::AccessLog],
            mappings: vec![ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC6.1".into() }],
            created_at: now,
        },
        Control {
            id: "A.9.2.1".into(),
            title: "User Registration and De-registration".into(),
            description: "A formal user registration and de-registration process shall be implemented to enable assignment of access rights.".into(),
            framework: Framework::Iso27001,
            category: "Access Control".into(),
            implementation_guidance: "Implement onboarding/offboarding procedures; automate user provisioning and de-provisioning.".into(),
            evidence_types: vec![EvidenceType::AccessLog, EvidenceType::AuditLog],
            mappings: vec![
                ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC6.2".into() },
                ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC6.3".into() },
            ],
            created_at: now,
        },
        Control {
            id: "A.9.4.1".into(),
            title: "Information Access Restriction".into(),
            description: "Access to information and application system functions shall be restricted in accordance with the access control policy.".into(),
            framework: Framework::Iso27001,
            category: "Access Control".into(),
            implementation_guidance: "Implement application-level access controls, enforce least privilege, review access rights regularly.".into(),
            evidence_types: vec![EvidenceType::AccessLog, EvidenceType::ConfigSnapshot],
            mappings: vec![
                ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC6.1".into() },
                ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC6.3".into() },
            ],
            created_at: now,
        },
        Control {
            id: "A.10.1.1".into(),
            title: "Policy on Cryptographic Controls".into(),
            description: "A policy on the use of cryptographic controls for protection of information shall be developed and implemented.".into(),
            framework: Framework::Iso27001,
            category: "Cryptography".into(),
            implementation_guidance: "Document encryption standards, key management procedures, and approved algorithms.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::ConfigSnapshot],
            mappings: vec![ControlMapping { framework: Framework::Soc2TypeII, control_id: "C1.1".into() }],
            created_at: now,
        },
        Control {
            id: "A.11.1.1".into(),
            title: "Physical Security Perimeter".into(),
            description: "Security perimeters shall be defined and used to protect areas that contain either sensitive or critical information and information processing facilities.".into(),
            framework: Framework::Iso27001,
            category: "Physical and Environmental Security".into(),
            implementation_guidance: "Define physical security zones, implement badge access, CCTV, and visitor management.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::AuditLog],
            mappings: vec![],
            created_at: now,
        },
        Control {
            id: "A.12.1.1".into(),
            title: "Documented Operating Procedures".into(),
            description: "Operating procedures shall be documented and made available to all users who need them.".into(),
            framework: Framework::Iso27001,
            category: "Operations Security".into(),
            implementation_guidance: "Document runbooks, playbooks, and operating procedures; make them accessible to relevant staff.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument],
            mappings: vec![ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC5.1".into() }],
            created_at: now,
        },
        Control {
            id: "A.12.6.1".into(),
            title: "Management of Technical Vulnerabilities".into(),
            description: "Information about technical vulnerabilities of information systems being used shall be obtained in a timely fashion.".into(),
            framework: Framework::Iso27001,
            category: "Operations Security".into(),
            implementation_guidance: "Implement vulnerability scanning, patch management process, and track remediation SLAs.".into(),
            evidence_types: vec![EvidenceType::ScanResult, EvidenceType::AuditLog],
            mappings: vec![ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC7.1".into() }],
            created_at: now,
        },
        Control {
            id: "A.13.1.1".into(),
            title: "Network Controls".into(),
            description: "Networks shall be managed and controlled to protect information in systems and applications.".into(),
            framework: Framework::Iso27001,
            category: "Communications Security".into(),
            implementation_guidance: "Implement network segmentation, firewalls, IDS/IPS, and network monitoring.".into(),
            evidence_types: vec![EvidenceType::ConfigSnapshot, EvidenceType::ScanResult],
            mappings: vec![],
            created_at: now,
        },
        Control {
            id: "A.14.2.1".into(),
            title: "Secure Development Policy".into(),
            description: "Rules for the development of software and systems shall be established and applied to developments within the organization.".into(),
            framework: Framework::Iso27001,
            category: "System Acquisition, Development and Maintenance".into(),
            implementation_guidance: "Define secure SDLC, code review requirements, security testing gates, and dependency scanning.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::ScanResult],
            mappings: vec![ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC8.1".into() }],
            created_at: now,
        },
        Control {
            id: "A.16.1.1".into(),
            title: "Responsibilities and Procedures for Incident Management".into(),
            description: "Management responsibilities and procedures shall be established to ensure a quick, effective, and orderly response to information security incidents.".into(),
            framework: Framework::Iso27001,
            category: "Information Security Incident Management".into(),
            implementation_guidance: "Define incident response plan, roles, escalation paths, and post-incident review procedures.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::IncidentReport],
            mappings: vec![ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC7.2".into() }],
            created_at: now,
        },
        Control {
            id: "A.17.1.1".into(),
            title: "Planning Information Security Continuity".into(),
            description: "The organization shall determine its requirements for information security and the continuity of information security management in adverse situations.".into(),
            framework: Framework::Iso27001,
            category: "Business Continuity Management".into(),
            implementation_guidance: "Develop BCP/DR plans, conduct tabletop exercises, test recovery procedures annually.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::SecurityAssessment],
            mappings: vec![
                ControlMapping { framework: Framework::Soc2TypeII, control_id: "A1.1".into() },
                ControlMapping { framework: Framework::Soc2TypeII, control_id: "A1.2".into() },
            ],
            created_at: now,
        },
        Control {
            id: "A.18.1.1".into(),
            title: "Identification of Applicable Legislation and Contractual Requirements".into(),
            description: "All relevant legislative, statutory, regulatory, and contractual requirements and the organization's approach to meet these requirements shall be explicitly identified.".into(),
            framework: Framework::Iso27001,
            category: "Compliance".into(),
            implementation_guidance: "Maintain a legal/regulatory register; assign compliance owners; conduct regular compliance reviews.".into(),
            evidence_types: vec![EvidenceType::PolicyDocument, EvidenceType::AuditLog],
            mappings: vec![ControlMapping { framework: Framework::Soc2TypeII, control_id: "CC9.1".into() }],
            created_at: now,
        },
    ]
}

// ─── Aggregation helpers ──────────────────────────────────────────────────────

pub fn all_controls() -> Vec<Control> {
    let mut controls = soc2_controls();
    controls.extend(iso27001_controls());
    controls
}

pub fn get_control(id: &str) -> Option<Control> {
    all_controls().into_iter().find(|c| c.id == id)
}

pub fn get_mappings(control_id: &str) -> Vec<ControlMapping> {
    get_control(control_id)
        .map(|c| c.mappings)
        .unwrap_or_default()
}
